// import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { ReactNode } from "react";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rabbit Finance",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div className="p-32 flex justify-center">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
